version: '3'

services: 
  backend:
    build: 
      context: server
    container_name: backend
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./server/.env  # Add the .env file from the server root folder
    tty: true
    ports: 
      - "5000:5000"
    command: npm run start
    depends_on:
      - db

  frontend:
    build: 
      context: client
    container_name: frontend
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    command: npm run start

  # MongoDB service (if you need MongoDB)
  db:
    container_name: mern-db
    image: mongo
    restart: always
    tty: true
    ports:
      - '27017:27017'
    networks:
      - node-network
      - mern-network

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
       - backend
       - frontend

networks: 
  node-network:
    driver: bridge

  mern-network:
    driver: bridge
